version: '3.5'

services:

  backend-gp-cv:
    build: backend/.
    container_name: gp_cv_backend
    ports:
      - '8000:8000'
    restart: unless-stopped
    networks:
      - mycustomnetwork2
        


  frontend-gp-cv:
    build: frontend/.
    container_name: gp_cv_frontend
    ports:
      - '8080:80'
    restart: unless-stopped
    networks:
      - mycustomnetwork2
       
    # environment:
    #   - 'CHATBOT_HOST=chatbot'
    #   - 'CHATBOT_PORT=8666'


networks:
  mycustomnetwork2:
    driver: bridge
    